cable.js support

diff --git a/.github/workflows/test-fetch.yml b/.github/workflows/test-fetch.yml
--- a/.github/workflows/test-fetch.yml
+++ b/.github/workflows/test-fetch.yml
@@ -4,7 +4,7 @@ on:
     paths:
       - 'test/fetch/**'
 jobs:
-  Run-Test:
+  Run-Regular-Fetch-Test:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
@@ -17,6 +17,31 @@ jobs:
           node fetch.js
 
           success="$(node fetch.js | tail -n 1)"
+          if echo "$success" | grep -q "SUCCESSFUL: Yes"; then
+            echo " " # placeholder idk
+          else
+            echo "--[ RESULTS ]------------------------"
+            echo "Fetch error."
+            exit 1
+          fi
+
+          
+          echo "--[ RESULTS ]------------------------"
+          echo "Successful fetch!"
+          exit 0
+  Run-Fetcher-Service-Test:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+        
+      - name: Test Fetcher Service JS
+        run: |
+          cd test/fetch
+          echo "--[ FETCH ]------------------------"
+          node cable.js
+
+          success="$(node cable.js | tail -n 2)"
           if echo "$success" | grep -q "SUCCESSFUL: Yes"; then
             echo " " # placeholder idk
           else
